### ISSUE TITLE
System crashes when calculating integral. 

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#128]
```
Int(((a+b)/(a^(1/3)+b^(1/3))-(a*b)^(1/3))/(a^(1/3)-b^(1/3))^2,a)
```

![image](https://user-images.githubusercontent.com/19369448/57586579-dfc34e00-7521-11e9-8e19-d8a3bc71f276.png)

There is stack trace:
```Java
java.lang.StackOverflowError
	at org.matheclipse.core.expression.AST3.forEach(AST3.java:363)
	at org.matheclipse.core.interfaces.IASTImpl.forEach(IASTImpl.java:317)
	at org.matheclipse.core.eval.EvalEngine.flattenSequences(EvalEngine.java:1721)
	at org.matheclipse.core.eval.EvalEngine.evalAttributes(EvalEngine.java:807)
	at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:1222)
	at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:1150)
	at org.matheclipse.core.eval.EvalEngine.evalArg(EvalEngine.java:518)
	at org.matheclipse.core.eval.EvalEngine.evalArgs(EvalEngine.java:564)
	at org.matheclipse.core.eval.EvalEngine.evalAttributes(EvalEngine.java:826)
	at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:1222)
	at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:1150)
	at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1707)
	at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1626)
	at org.matheclipse.core.builtin.Structure$Apply$1.apply(Structure.java:186)
	at org.matheclipse.core.builtin.Structure$Apply$1.apply(Structure.java:183)
	at org.matheclipse.core.interfaces.IASTMutableImpl.setArgs(IASTMutableImpl.java:21)
	at org.matheclipse.core.interfaces.IASTMutableImpl.setArgs(IASTMutableImpl.java:35)
	at org.matheclipse.core.builtin.Structure$Apply.evaluate(Structure.java:183)
	at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:1218)
	at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:1150)
	at org.matheclipse.core.eval.EvalEngine.evalArg(EvalEngine.java:518)
	at org.matheclipse.core.eval.EvalEngine.access$000(EvalEngine.java:59)
	at org.matheclipse.core.eval.EvalEngine$2.accept(EvalEngine.java:600)
	at org.matheclipse.core.eval.EvalEngine$2.accept(EvalEngine.java:596)
	at org.matheclipse.core.expression.AST2.forEach(AST2.java:322)
	at org.matheclipse.core.eval.EvalEngine.evalArgs(EvalEngine.java:596)
	at org.matheclipse.core.eval.EvalEngine.evalAttributes(EvalEngine.java:826)
	at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:1222)
	at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:1150)
	at org.matheclipse.core.eval.EvalEngine.evalArg(EvalEngine.java:518)
	at org.matheclipse.core.eval.EvalEngine.evalArgs(EvalEngine.java:564)
	at org.matheclipse.core.eval.EvalEngine.evalASTArg1(EvalEngine.java:677)
	at org.matheclipse.core.eval.EvalEngine.evalAttributes(EvalEngine.java:793)
        ...
```

**Comment by axkr** [comment]
in my dev environment I get the result:


```
a+3/2*a^(2/3)*b^(1/3)+6*a^(1/3)*b^(2/3)-3/2*a^(1/3)*(a*b)^(1/3)-6*b^(1/3)*(a*b)^(
1/3)+(3*b*(a*b)^(1/3))/(a^(1/3)*(a^(1/3)-b^(1/3)))+(-9*b^(2/3)*(a*b)^(1/3)*Log(a^(
1/3)-b^(1/3)))/a^(1/3)+3*b*Log(a-a^(2/3)*b^(1/3)-a^(1/3)*b^(2/3)+b)+9*b^(4/3)*Rubi`subst[Integrate(a/(a^
3-4/3*a*b^(2/3)+16/27*b),a),a,a^(1/3)-b^(1/3)/3]
```

Although no complete solution the StackOverflow  can probably solved with a greater stack size per thread (ie. `-Xss...` option)

**Comment by tranleduy2000** [comment]
Could you add the recursion check to avoid this error when running on low-end device?

**Comment by axkr** [comment]
Did you already try to reduce Config.INTEGRATE_RUBI_RULES_RECURSION_LIMIT ?

**Comment by tranleduy2000** [comment]
I reduce the INTEGRATE_RUBI_RULES_RECURSION_LIMIT but it still throws error.
There is limit with JVM on Android device.

Another expression cause system crashes: 
```
Integrate(Log(x^3)/E^(2+x),{x,1,2})
```

![image](https://user-images.githubusercontent.com/19369448/58689780-23d3a100-83b2-11e9-86a0-64e1074934a4.png)
